# SwiftLint configuration for CCMate

# Paths to include
included:
  - CCMate
  - CCMateTests

# Paths to exclude
excluded:
  - Carthage
  - Pods
  - .build
  - build
  - DerivedData
  - ${PWD}/**/*.generated.swift

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - line_length
  - file_length
  - type_body_length
  - function_body_length

# Rule configurations
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - url

force_cast: warning
force_try: warning

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

large_tuple:
  warning: 3
  error: 4

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60